### ISSUE TITLE
containerize preston for deployment on acis host

### ISSUE THREAD

**Issue by jhpoelen** [bio-linker/organization#4]

**Comment by jhpoelen** [comment]
Hey @mjcollin - I added some info on installing Preston on servers, with examples of docker and systemd service/timer. What do you think should be done extra to make Preston easier to deploy? 

See https://github.com/bio-guoda/preston#docker
and 
https://github.com/bio-guoda/preston#running-periodically

**Comment by mjcollin** [comment]
I set preston.acis.ufl.edu up with your user and the docker container version. I'm unable to get our config management system to start the container correctly but starting from the command line works fine. It's chugging now. I'll see what's in the data dir tomorrow.

**Comment by jhpoelen** [comment]
@mjcollin great! If you have some suggestions on how to make the install / run process easier, please holler.

**Comment by mjcollin** [comment]
Re-evaluated and decided that system service is better for our deployment on permanent infrastructure, reworking preston.acis.ufl.edu that way.
